
const r_list = [
        
    {title: 'My Wonderful Family',
    p1: 'I live in a house near the mountains. I have two brothers and one sister, and I was born last. My father teaches mathematics, and my mother is a nurse at a big hospital. My brothers are very smart and work hard in school. My sister is a nervous girl, but she is very kind. My grandmother also lives with us. She came from Italy when I was two years old. She has grown old, but she is still very strong. She cooks the best food!',
    p2: 'My family is very important to me. We do lots of things together. My brothers and I like to go on long walks in the mountains. My sister likes to cook with my grandmother. On the weekends we all play board games together. We laugh and always have a good time. I love my family very much.',
    p3: '',
    test: [
        {num: 1,
        question: 'My mother is a...',
        ans1: 'Doctor',
        ans2: 'Nurse',
        ans3: 'Writer',
        ans4: 'Waitress',
        right: '2'},
        {num: 2,
        question: 'My house is near the...',
        ans1: 'City',
        ans2: 'Monastery',
        ans3: 'Mountains',
        ans4: 'Italy',
        right: '3'},
        {num: 3,
        question: 'How old was I when my grandmother came?',
        ans1: 'Three years old',
        ans2: 'Just born',
        ans3: 'Ten years old',
        ans4: ' Two years old',
        right: '4'},
        {num: 4,
        question: 'On the weekends, we...',
        ans1: 'Play board games together',
        ans2: 'Go to a movie',
        ans3: 'Clean the house',
        ans4: 'Cook pasta',
        right: '1'},
        {num: 5,
        question: 'My sister is kind, but also...',
        ans1: 'Mean',
        ans2: 'Quiet',
        ans3: 'Nervous',
        ans4: 'Strong',
        right: '3'},
    ],},
    
    {title: 'My day',
    p1: 'First, I wake up. Then, I get dressed. I walk to school. I do not ride a bike. I do not ride the bus. I like to go to school. It rains. I do not like rain. I eat lunch. I eat a sandwich and an apple.',
    p2: 'I play outside. I like to play. I read a book. I like to read books. I walk home. I do not like walking home. My mother cooks soup for dinner. The soup is hot. Then, I go to bed. I do not like to go to bed.',
    p3: '',
    test: [
        {num: 1,
        question: 'What happens first?',
        ans1: 'Wake up',
        ans2: 'Eat lunch',
        ans3: 'Get dressed',
        ans4: 'Walk to school',
        right: '1'},
        {num: 2,
        question: 'What do I like?',
        ans1: 'Walking home',
        ans2: 'Going to bed',
        ans3: 'Rain',
        ans4: 'Books',
        right: '4'},
        {num: 3,
        question: 'How do I go to school?',
        ans1: 'I drive a car',
        ans2: 'I ride a bike',
        ans3: 'I ride the bus',
        ans4: 'I walk',
        right: '4'},
        {num: 4,
        question: 'What do I eat for dinner?',
        ans1: 'Soup',
        ans2: 'Apple',
        ans3: 'Pie',
        ans4: 'Sandwich',
        right: '1'},
        {num: 5,
        question: 'What do I not like?',
        ans1: 'Going to school',
        ans2: 'Soup',
        ans3: 'Going to bed',
        ans4: 'Playing',
        right: '3'},
    ],},

    {title: 'My name is John',
    p1: 'Hi! Nice to meet you! My name is John Smith. I am 19 and a student in college. I go to college in New York. My favorite courses are Geometry, French, and History. English is my hardest course. My professors are very friendly and smart. It’s my second year in college now. I love it!',
    p2: 'I live in a big house on Ivy Street. It is near the college campus. I share the house with three other students. Their names are Bill, Tony, and Paul. We help each other with homework. On the weekend, we play football together.',
    p3: 'I have a younger brother. He just started high school. He is 14 and lives with my parents. They live on Mulberry Street in Boston. Sometimes they visit me in New York. I am happy when they visit. My Mom always brings me sweets and candy when they come. I really miss them, too!',
    test: [
        {num: 1,
        question: 'Where does John Smith go to college?',
        ans1: 'Boston',
        ans2: 'Paris',
        ans3: 'Berlin',
        ans4: 'New York',
        right: '4'},
        {num: 2,
        question: 'What is John Smith’s hardest course?',
        ans1: 'French',
        ans2: 'Art',
        ans3: 'Math',
        ans4: 'English',
        right: '4'},
        {num: 3,
        question: 'Who shares a house with John Smith?',
        ans1: 'Frank, Tony, and Mike',
        ans2: 'Anna, Margaret, and Tanya',
        ans3: 'Bill, Tony, and Paul',
        ans4: 'Bill, John, and Tom',
        right: '3'},
        {num: 4,
        question: 'How old is John Smith`s younger brother?',
        ans1: 'seven',
        ans2: 'thirteen',
        ans3: 'eleven',
        ans4: 'fourteen',
        right: '4'},
        {num: 5,
        question: 'What does John Smith`s Mom bring him when they visit?',
        ans1: 'Sweets and candy',
        ans2: 'Flowers and coffee',
        ans3: 'Fruits and vegetables',
        ans4: 'Candy and ice cream',
        right: '1'},
    ],},
    
    {title: 'Our Vacation',
    p1: 'Every year we go to Florida. We like to go to the beach.',
    p2: 'My favorite beach is called Emerson Beach. It is very long, with soft sand and palm trees. It is very beautiful. I like to make sandcastles and watch the sailboats go by. Sometimes there are dolphins and whales in the water!',
    p3: 'Every morning we look for shells in the sand. I found fifteen big shells last year. I put them in a special place in my room. This year I want to learn to surf. It is hard to surf, but so much fun! My sister is a good surfer. She says that she can teach me. I hope I can do it!',
    test: [
        {num: 1,
        question: 'My favorite beach is...',
        ans1: 'Long Beach',
        ans2: 'Palm Beach',
        ans3: 'Surf Beach',
        ans4: 'Emerson Beach',
        right: '4'},
        {num: 2,
        question: 'What animals do I see in the water?',
        ans1: 'Sharks',
        ans2: 'Starfish',
        ans3: 'Dolphins',
        ans4: 'Dogs',
        right: '3'},
        {num: 3,
        question: 'How many shells did I find last year?',
        ans1: 'Fifty',
        ans2: 'Twelve',
        ans3: 'Five',
        ans4: 'Fifteen',
        right: '4'},
        {num: 4,
        question: 'What do I want to learn this year?',
        ans1: 'Swimming',
        ans2: 'How to find shells',
        ans3: 'Surfing',
        ans4: 'Sailing',
        right: '3'},
        {num: 5,
        question: 'Where did I put my shells last year?',
        ans1: 'In the garage',
        ans2: 'In a box',
        ans3: 'In my room',
        ans4: 'In Florida',
        right: '3'},
    ],},
    
    {title: 'Preparing food',
    p1: 'Jack was hungry. He walked to the kitchen. He got out some eggs. He took out some oil. He placed a skillet on the stove. Next, he turned on the heat. He poured the oil into the skillet. He cracked the eggs into a bowl. He stirred the eggs. Then, he poured them into the hot skillet. He waited while the eggs cooked. They cooked for two minutes. He heard them cooking. They popped in the oil.',
    p2: 'Next, Jack put the eggs on a plate. He placed the plate on the dining room table. Jack loved looking at his eggs. They looked pretty on the white plate. He sat down in the large wooden chair. He thought about the day ahead. He ate the eggs with a spoon. They were good.',
    p3: 'He washed the plate with dishwashing soap. Then, he washed the pan. He got a sponge damp. Finally, he wiped down the table. Next, Jack watched TV.',
    test: [
        {num: 1,
        question: 'What food was cooked?',
        ans1: 'Eggs',
        ans2: 'Rice',
        ans3: 'Pork',
        ans4: 'Fish',
        right: '1'},
        {num: 2,
        question: 'Where did Jack eat the eggs?',
        ans1: 'In the kitchen',
        ans2: 'In front of the TV',
        ans3: 'At the dining room table',
        ans4: 'In his room',
        right: '3'},
        {num: 3,
        question: 'How long did the eggs cook?',
        ans1: '3 minutes',
        ans2: '10 minutes',
        ans3: '5 minutes',
        ans4: '2 minutes',
        right: '4'},
        {num: 4,
        question: 'What was the chair made of?',
        ans1: 'Metal',
        ans2: 'Stone',
        ans3: 'We do not know',
        ans4: 'Wood',
        right: '4'},
        {num: 5,
        question: 'Jack cooked in a skillet. What is another word for skillet?',
        ans1: 'Pan',
        ans2: 'Microwave',
        ans3: 'Slow cooker',
        ans4: 'Oven',
        right: '1'},
    ],},
    
    {title: 'The House',
    p1: 'Mr. and Mrs. Smith have one son and one daughter. The son`s name is John. The daughter`s name is Sarah.',
    p2: 'The Smiths live in a house. They have a living room. They watch TV in the living room. The father cooks food in the kitchen. They eat in the dining room. The house has two bedrooms. They sleep in the bedrooms. They keep their clothes in the closet. There is one bathroom. They brush their teeth in the bathroom.',
    p3: 'The house has a garden. John and Sarah play in the garden. They have a dog. John and Sarah like to play with the dog.',
    test: [
        {num: 1,
        question: 'How many children do Mr. and Mrs. Smith have?',
        ans1: 'No children',
        ans2: 'One daughter',
        ans3: 'One son and one daughter',
        ans4: 'One son',
        right: '3'},
        {num: 2,
        question: 'Who cooks in the kitchen?',
        ans1: 'Mother',
        ans2: 'Father',
        ans3: 'John',
        ans4: 'Sarah',
        right: '2'},
        {num: 3,
        question: 'Where does the family eat?',
        ans1: 'Living rooms',
        ans2: 'Dining room',
        ans3: 'Kitchen',
        ans4: 'Bedroom',
        right: '2'},
        {num: 4,
        question: 'How many bedrooms are in the house?',
        ans1: 'Three',
        ans2: 'One',
        ans3: 'Four',
        ans4: 'Two',
        right: '4'},
        {num: 5,
        question: 'What do John and Sarah do in the garden?',
        ans1: 'Brush their teeth',
        ans2: 'Play',
        ans3: 'Sleep',
        ans4: 'Cook',
        right: '2'},
    ],},
    
]

export {r_list}