import persPronouns from '../img/personal_pronouns.png'
import plural from '../img/plural.png'
import articles from '../img/articles.jpg'
import toBe from '../img/toBe.png'
const t_list = [
        
    {title: 'Личные местоимения',
    p1: 'Местоимение — слово, которое заменяет существительное. Местоимение не называет предмет или лицо, а лишь обозначает его. Есть несколько особенностей английских местоимений:',
    p2: 'I (я) в английском языке всегда пишется с большой буквы.',
    p3: 'He (он) и she (она) используются для обозначения лиц мужского и женского пола соответственно. Также они используются, когда вы говорите о своих домашних питомцах и вам нужно обозначить их пол.',
    p4: 'It (оно, это) используется для обозначения неодушевленных предметов, а также животных.',
    p5: 'We (мы) обозначает говорящего вместе с группой лиц. They (они) употребляется для обозначения одушевленных и неодушевленных предметов во множественном числе.',
    p6: 'You (ты, вы, Вы) обозначает обращение «ты», обращение к группе людей «вы» и вежливое обращение к одному человеку «Вы».',
    p7: 'У личных местоимений есть три основные формы:',
    p8: '1. Именительный падеж: местоимение обозначает предмет или человека, который совершает действие. При этом местоимение выступает в роли подлежащего. I am a manager. — Я менеджер. It (radio) is working. — Оно (радио) работает',
    p9: '2. Объектный падеж: на местоимение направлено действие. Здесь местоимение выступает в роли дополнения и отвечает на вопросы «Кому?», «Кого?», «Кем?», а для неодушевленных предметов — «Что?». Jim is writing a letter to me. — Джим пишет письмо (кому?) мне. She is cooking for him. — Она готовит для (кого?) него.',
    p10: '3. Притяжательный падеж: местоимение показывает принадлежность предмета и отвечает на вопрос «Чей?». Nick is my friend. — Ник (чей?) мой друг. It’s your cup. — Это (чья?) твоя кружка.',
    img: persPronouns,
    test: [
        {num: 1,
        question: '… am beautiful.',
        ans1: ' She',
        ans2: ' We',
        ans3: ' He',
        ans4: ' I',
        right: '4'},
        {num: 2,
        question: '… (он) is a teacher.',
        ans1: 'He',
        ans2: 'I',
        ans3: ' They',
        ans4: ' She',
        right: '1'},
        {num: 3,
        question: '… (мы) are clever.',
        ans1: ' They',
        ans2: ' He',
        ans3: ' You',
        ans4: ' We',
        right: '4'},
        {num: 4,
        question: 'She is looking at … (него).',
        ans1: ' Her',
        ans2: ' Him',
        ans3: ' Them',
        ans4: ' It',
        right: '2'},
        {num: 5,
        question: 'I am cooking … (это).',
        ans1: 'Us',
        ans2: ' It',
        ans3: 'Him',
        ans4: ' Her',
        right: '2'},
        {num: 6,
        question: 'John is running towards … (к ней).',
        ans1: ' Them',
        ans2: ' You',
        ans3: ' Her',
        ans4: ' Us',
        right: '3'},
        {num: 7,
        question: 'It is … (наша) book.',
        ans1: ' Our',
        ans2: ' Their',
        ans3: ' His',
        ans4: ' Her',
        right: '1'},
        {num: 8,
        question: 'She is … (твоя) sister.',
        ans1: ' Your',
        ans2: ' Our',
        ans3: ' Their',
        ans4: ' His',
        right: '1'},    
        {num: 9,
        question: '… (их) shoes are dirty.',
        ans1: ' His',
        ans2: ' My',
        ans3: ' Our',
        ans4: ' Their',
        right: '4'},
        {num: 10,
        question: '… (его) cup is green.',
        ans1: ' Him ',
        ans2: ' Her ',
        ans3: ' Our ',
        ans4: ' His ',
        right: '4'},
    ]},
    
    {title: 'Множественное число',
    p1: 'В английском языке, как и в русском, все слова делятся на исчисляемые и неисчисляемые. Это важно понимать при образовании множественного числа того или иного слова. Исчисляемые существительные обозначают те предметы, которые можно посчитать, например: table (стол), book (книга), apple (яблоко). Неисчисляемые существительные — это абстрактные понятия, жидкости, продукты и т. д., то есть то, что нельзя посчитать. Например: знания (knowledge), вода (water), мясо (meat), мука (flour). У этих слов нет множественного или единственного числа',
    p2: 'Обычно множественное число имен существительных образуется путем добавления к слову окончания -s: book – books (книга – книги). Однако есть несколько особенностей правописания:',
    p3: 'Если слово заканчивается на -o, -s, -ss, -sh, -ch, -x, то добавляем окончание -es: hero – heroes (герой – герои), bus – buses (автобус – автобусы).',
    p4: 'Исключения: photo – photos (фотография – фотографии), video – videos (видеозапись – видеозаписи), radio – radios (радио – несколько радио), rhino – rhinos (носорог – носороги), piano – pianos (фортепиано – несколько фортепиано), hippo – hippos (бегемот – бегемоты)',
    p5: 'Если слово заканчивается на -f, -fe, то меняем окончание на -ves: knife – knives (нож – ножи), leaf – leaves (лист – листья), wife – wives (жена – жены).',
    p6: 'Исключения: roof – roofs (крыша – крыши), giraffe – giraffes (жираф – жирафы), cliff – cliffs (утес – утесы)',
    p7: 'Если слово заканчивается на -y, перед которой стоит согласная буква, то -y мы меняем на -ies: body – bodies (тело – тела)',
    p8: 'Если слово заканчивается на -y, перед которой стоит гласная, то добавляем окончание -s: boy – boys (мальчик – мальчики)',
    p9: 'В английском языке есть и слова-исключения, которые образуют множественное число не по правилам. Такие слова надо просто выучить наизусть, к счастью, их не очень много',
    img: plural,
    test: [
        {num: 1,
        question: 'Множественное число для слова pencil',
        ans1: 'Penciles',
        ans2: 'Pencils',
        ans3: 'Penciles',
        ans4: 'Pens',
        right: '2'},
        {num: 2,
        question: 'Множественное число для слова toy',
        ans1: 'Tos',
        ans2: 'Tois',
        ans3: 'Toyes',
        ans4: 'Toys',
        right: '4'},
        {num: 3,
        question: 'Множественное число для слова man',
        ans1: 'Men',
        ans2: 'Man',
        ans3: 'Mans',
        ans4: 'Manes',
        right: '1'},
        {num: 4,
        question: 'Множественное число для слова bush',
        ans1: 'Bushs',
        ans2: 'Bushies',
        ans3: 'Bush',
        ans4: 'Bushes',
        right: '4'},
        {num: 5,
        question: 'Множественное число для слова child',
        ans1: 'Childs',
        ans2: 'Childes',
        ans3: 'Childrens',
        ans4: 'Children',
        right: '4'},
        {num: 6,
        question: 'Множественное число для слова leaf',
        ans1: 'Leafes',
        ans2: 'Leafs',
        ans3: 'Leaves',
        ans4: 'Leavs',
        right: '3'},
        {num: 7,
        question: 'Множественное число для слова photo',
        ans1: 'Photoes',
        ans2: 'Photos',
        ans3: 'Photo',
        ans4: 'Photes',
        right: '2'},
        {num: 8,
        question: 'Множественное число для слова lady',
        ans1: 'Ladies',
        ans2: 'Ladyes',
        ans3: 'Ladys',
        ans4: 'Lady',
        right: '1'},    
        {num: 9,
        question: 'Множественное число для слова sheep',
        ans1: 'Sheeps',
        ans2: 'Sheep',
        ans3: 'Sheepes',
        ans4: 'Sheepies',
        right: '2'},
        {num: 10,
        question: 'Множественное число для слова word',
        ans1: 'Words',
        ans2: 'Wordes',
        ans3: 'Wordies',
        ans4: 'Word',
        right: '1'},
    ]},

    {title: 'Артикли',
    p1: 'В английском языке есть два типа артикля: определенный и неопределенный. Они не переводятся на русский язык. Перед существительным в единственном числе в подавляющем большинстве случаев надо ставить какой-то из этих артиклей',
    p2: 'Неопределенный артикль a/an употребляется в следующих случаях:',
    p3: 'Мы называем любой, какой-то неопределенный предмет, причем он у нас один, или впервые упоминаем предмет в речи: It is a book. — Это книга.',
    p4: 'Мы говорим о профессии человека или указываем на его принадлежность к какой-то группе: He is a teacher. — Он учитель.',
    p5: 'Определенный артикль the мы ставим, когда речь идет о конкретном знакомом нам предмете. Этот артикль может стоять перед существительным в единственном или множественном числе. Он употребляется в следующих случаях:',
    p6: 'Мы уже упомянули предмет ранее в своей речи: I see a shop. The shop is big. — Я вижу магазин. (Этот) Магазин большой.',
    p7: 'Мы говорим о предмете, который в данном контексте является единственным в своем роде, его невозможно спутать с чем-то другим: Honey, I’m washing the car. — Дорогая, я мою машину. (в семье одна машина, поэтому мы говорим о конкретном предмете)',
    p8: 'Мы говорим о единственном в своем роде предмете, другого такого не существует: солнце, луна, мир, президент Франции и т. д.: The earth is our home. — Земля — наш дом.',
    p9: 'Мы не используем никаких артиклей, когда: Мы говорим о чем-то в общем: Life is wonderful. — Жизнь удивительна. (мы говорим о жизни в общем как о явлении, а не о жизни какого-то человека)',
    p10: 'Мы говорим о времени года, месяце или дне недели в общем, не указывая на конкретный день недели / месяц / время года: Summer is the hottest season. — Лето — самый жаркий сезон. (речь идет не о конкретном лете, а в целом об этом сезоне года)',
    img: articles,
    test: [
        {num: 1,
        question: 'Look at ... boy!',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '3'},
        {num: 2,
        question: 'What is ... happiness?',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '2'},
        {num: 3,
        question: 'It is ... apple.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '4'},
        {num: 4,
        question: 'I see a building. ... building is small.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '3'},
        {num: 5,
        question: 'I drink a lot of ... water.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '2'},
        {num: 6,
        question: 'I am ... manager.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '1'},
        {num: 7,
        question: '... september is my favourite month.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '2'},
        {num: 8,
        question: '... elephants are large animals.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '2'},    
        {num: 9,
        question: 'He is ... doctor.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '1'},
        {num: 10,
        question: 'He is eating ... meat.',
        ans1: 'A',
        ans2: '-',
        ans3: 'The',
        ans4: 'An',
        right: '2'},
    ]},
    
    {title: 'Глагол to be',
    p1: 'В английском предложении всегда есть глагол. И если по-русски мы можем сказать «Я доктор», «Мэри красивая», «Мы в госпитале», то в английском языке это недопустимо: во всех этих случаях после подлежащего должен стоять глагол to be. Поэтому вы можете запомнить простое правило: если в предложении нет обычных глаголов, значит, нужен глагол to be',
    p2: 'У глагола to be есть три формы:',
    p3: 'Am добавляем к местоимению I, когда мы говорим о себе: I am beautiful. — Я красивый.',
    p4: 'Is ставим после местоимений he, she, it: She is beautiful. — Она красивая.',
    p5: 'Are употребляем после you, we, they: You are beautiful. — Ты красивый.',
    p6: 'Глагол to be в английском языке чаще всего употребляется в следующих случаях:',
    p7: 'Сообщаем, кем является человек (имя, профессия и т. п.): I am a doctor. — Я доктор.',
    p8: 'Сообщаем, каким качеством обладает человек или предмет: Mary is beautiful. — Мэри красивая.',
    p9: 'Сообщаем, где находится человек или предмет: We are at the hospital. — Мы в госпитале.',
    p10: 'Предложения с глаголом to be в настоящем времени строятся следующим образом:',
    img: toBe,
    test: [
        {num: 1,
        question: 'She ... beautiful. (Она красивая.)',
        ans1: 'Are',
        ans2: 'Am',
        ans3: 'Is',
        ans4: 'Not',
        right: '3'},
        {num: 2,
        question: 'You ... at work. (Ты на работе.)',
        ans1: 'Are',
        ans2: 'Be',
        ans3: 'Is',
        ans4: 'Am',
        right: '1'},
        {num: 3,
        question: '... he a shop-assistant? (Он продавец?)',
        ans1: 'Are',
        ans2: 'Am',
        ans3: 'Be',
        ans4: 'Is',
        right: '4'},
        {num: 4,
        question: 'They ... rich. (Они не богаты.)',
        ans1: 'Is not',
        ans2: 'Aren`t',
        ans3: 'Am not',
        ans4: 'Be not',
        right: '2'},
        {num: 5,
        question: 'It (book) ... interesting.(Она (книга) интересная.)',
        ans1: 'Be',
        ans2: 'Are',
        ans3: 'Am',
        ans4: 'Is',
        right: '4'},
        {num: 6,
        question: 'We ... at the school. (Мы в школе.)',
        ans1: 'Are',
        ans2: 'Is',
        ans3: 'Am',
        ans4: 'Be',
        right: '1'},
        {num: 7,
        question: 'She ... tall. (Она не высокая)',
        ans1: 'Are not',
        ans2: 'Am not',
        ans3: 'Is',
        ans4: 'Is not',
        right: '4'},
        {num: 8,
        question: 'I ... a teacher. (Я учитель.)',
        ans1: 'Am',
        ans2: 'Is',
        ans3: 'Are',
        ans4: 'Am not',
        right: '1'},    
        {num: 9,
        question: '... they angry? (Они злые?)',
        ans1: 'Be',
        ans2: 'Is',
        ans3: 'Are',
        ans4: 'Am',
        right: '3'},
        {num: 10,
        question: 'It ... a book. (Это книга.)',
        ans1: 'Are',
        ans2: 'Be',
        ans3: 'Am',
        ans4: 'Is',
        right: '4'},
    ]},
    
]

export {t_list}