const v_list = [
        
    {title: 'Город',
    words: [
        {word: 'capital',
        translation: 'столица',
        },
        {word: 'city',
        translation: 'большой город',
        },
        {word: 'town',
        translation: 'городок',
        },
        {word: 'lawn',
        translation: 'лужайка',
        },
        {word: 'square',
        translation: 'площадь',
        },
        {word: 'street',
        translation: 'улица',
        },
        {word: 'palace',
        translation: 'дворец',
        },
        {word: 'a view of',
        translation: 'вид на',
        },
        {word: 'famous',
        translation: 'известный',
        },
        {word: 'be proud of',
        translation: 'гордиться',
        },
        {word: 'main',
        translation: 'главный',
        },
        {word: 'narrow',
        translation: 'узкий',
        },
        {word: 'bridge',
        translation: 'мост',
        },
        {word: 'church',
        translation: 'церковь',
        },
        {word: 'market',
        translation: 'рынок',
        },
        {word: 'wide',
        translation: 'широкий',
        },
    ],},
    
    {title: 'Семья',
    words: [
        {word: 'parents',
        translation: 'родители',
        },
        {word: 'father',
        translation: 'отец',
        },
        {word: 'mother',
        translation: 'мать',
        },
        {word: 'son',
        translation: 'сын',
        },
        {word: 'daughter',
        translation: 'дочь',
        },
        {word: 'old',
        translation: 'старый',
        },
        {word: 'elder',
        translation: 'старший',
        },
        {word: 'cousin',
        translation: 'двоюродный брат/сестра',
        },
        {word: 'sibling',
        translation: 'родной брат/сестра',
        },
        {word: 'twins',
        translation: 'близнецы',
        },
        {word: 'relative',
        translation: 'родственник',
        },
        {word: 'aunt',
        translation: 'тетя',
        },
        {word: 'uncle',
        translation: 'дядя',
        },
        {word: 'niece',
        translation: 'племянница',
        },
        {word: 'young',
        translation: 'молодой',
        },
        {word: 'close',
        translation: 'близкий',
        },
        {word: 'younger',
        translation: 'младший',
        },
        {word: 'nephew',
        translation: 'племянник',
        },
    ],},

    {title: 'Путешествия',
    words: [
        {word: 'trip to',
        translation: 'поездка в',
        },
        {word: 'all over the world',
        translation: 'по всему миру',
        },
        {word: 'get to',
        translation: 'добраться до',
        },
        {word: 'visit different countries',
        translation: 'посетить разные страны',
        },
        {word: 'travel to',
        translation: 'путешествовать в',
        },
        {word: 'museums and galleries',
        translation: 'музеи и галереи',
        },
        {word: 'sights',
        translation: 'достопримечательности',
        },
        {word: 'leave',
        translation: 'уехать из',
        },
        {word: 'spend a week in',
        translation: 'провести неделю в',
        },
        {word: 'on the way to',
        translation: 'по дороге',
        },
        {word: 'during the trip',
        translation: 'во время поездки',
        },
        {word: 'stay at a hotel',
        translation: 'остановиться в отеле',
        },
        {word: 'try local food',
        translation: 'пробовать местную пищу',
        },
        {word: 'buy souvenirs',
        translation: 'покупать сувениры',
        },
        {word: 'exciting',
        translation: 'увлекательный',
        },
        {word: 'unusual',
        translation: 'необычный',
        },
        {word: 'enjoy the trip',
        translation: 'получить удовольствие от поездки',
        },
        {word: 'come back home',
        translation: 'вернуться домой',
        },
    ],},
    
    
    
]

export {v_list}